name: pytorch-custom-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=25.0
  - conda-forge::pandas>=2.0.0
  - conda-forge::numpy>=1.24.0
  - conda-forge::pytorch
  - conda-forge::scikit-learn
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - pip:
    - transformers
    - rouge-score
    - nltk
    - fastapi
    - uvicorn
    - emoji
    - azureml-mlflow
    - azureml-core
variables:
  PYTHONPATH: /azureml-envs/pytorch-custom-conda/lib/python3.9/site-packages
  CONDA_DLL_SEARCH_MODIFICATION_ENABLE: "1"