name: pytorch-custom-conda
dependencies:
  - python=3.9
  - pip
  - pip:
      - --upgrade pip  # Ensure pip is up to date
      - pandas  # Ensure pandas installs first
      - torch
      - transformers
      - scikit-learn
      - rouge-score
      - nltk
      - fastapi
      - uvicorn
      - matplotlib
      - numpy
      - seaborn
      - emoji
      - azureml-mlflow
      - azureml-core
channels:
  - conda-forge
