$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: python notebooks/summarizer.py
code: .
environment: 
  name: pytorch-custom-env
  version: 14
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
compute: azureml:spoof-compute
experiment_name: summarization_experiment
description: "Training a summarization model using TinyLlama"
