$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: python train.py
code: .
environment: azureml:AzureML-pytorch-2.0-ubuntu20.04-py38-cuda11-gpu
compute: azureml:my-compute
experiment_name: summarization_experiment
output: azure_output/
